name = "twilight-butterfly-76d6"
main = "worker.js"
compatibility_date = "2023-08-23"

[unsafe.metadata.observability]
enabled = true


mtls_certificates = [
  { binding = "MY_CERT", certificate_id = "ba1bc205-fbdf-4e1d-88eb-e59f9ea8cd52" }
]